- Get-DscResourceTypeInformation.ps1
- build.ps1
- templates/dsc_provider.eps
- templates/dsc_type.eps
- templates/resource_api/lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
- templates/resource_api/lib/puppet/provider/dsc_base_provider/invoke_dsc_resource_postscript.ps1.erb
This set of commits is fairly heavy and includes some significant refactoring, bug fixing, and improvements.
Highlights include:
- Removal of need for undocumented CSV to specify which module to puppetize
- Fix file encoding of templated files (remove the BOM)
- Update type generation to include whether or not the types are mandatory and include their help information, if discoverable
- Re-use a single method (`invoke_set_method`) for the create, update, and delete calls in the provider
- Ensure the resultant provider implementation is idempotent and can return property-by-property change reporting by implementing the simple_get_filter feature
The build script defaults to creating the Puppet module `powershellget` by vendoring and puppetizing the …
> (IAC-647) Improve type generation and make provider idempotent

- build.ps1
- src/functions/Get-DscResourceTypeInformation.ps1
- src/internal/functions/Get-DscResourceParameterInfo.ps1
- src/puppet.dsc.psd1
- src/tests/functions/Get-DscResourceParameterInfo.Tests.ps1
- src/tests/functions/Get-DscResourceTypeInformation.Tests.ps1
- src/tests/pester.ps1
- src/xml/puppet.dsc.Types.ps1xml
This PR is an example of decomposing a public function for testability and includes unit tests for the public function, `Get-DscResourceTypeInformation` and the private function it depends upon, `Get-DscResourceParameterInfo`.
> (IAC-667) Ensure Get-DscResourceTypeInformation has test coverage

- appveyor.yml
- extras/install.ps1
This commit ensures that the build script will attempt to run after
the pester CI tests so we get fast feedback in the form of a loose
acceptance test; this is not a replacement for proper acceptance
testing, just a quick bandaid.
> (MAINT) Add full build proc to CI

- src/internal/templates/static/lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
Prior to this commit the methods for the base provider wrote very noisy
notification alerts at every stage of processing. These have been moved
to debug logs, as that is what they really represent.
> (MAINT) Make Puppet runs quieter

- extras/install.ps1
Encountered issues installing the latest version (2.2.4) of the PowerShellGet module:
```powershell
PackageManagement\Install-Package : The module 'PowerShellGet' cannot be installed because the catalog signature in               
'PowerShellGet.cat' does not match the hash generated from the module.                                                            
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21                                    
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters                                                       
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                       
+ CategoryInfo          : InvalidOperation: …
```
> (maint) Pin PowerShellGet module to ver 2.2.3

- src/internal/functions/Get-DscResourceParameterInfo.ps1
- src/internal/functions/Get-PuppetDataType.ps1
- src/internal/functions/Get-ShortType.ps1
- src/internal/functions/Get-TypeContent.ps1
- src/internal/functions/Test-EmbeddedInstance.ps1
- src/puppet.dsc.psd1
- src/tests/functions/Get-DscResourceParameterInfo.Tests.ps1
- src/tests/functions/Get-EmbeddedInstance.Tests.ps1
- src/tests/functions/Get-PuppetDataType.Tests.ps1
- src/tests/functions/Get-ShortType.Tests.ps1
Prior to this commit the module relied on the `Types.ps1xml` file to munge and alias DSC Resource property information to make processing easier in other functions. This was useful but at the cost of being very hard to reason about, review, update, and also impossible to usefully test with the given tools.
This commit removes our reliance on the types file entirely, moving the relevant functionality into private functions and updating the logic elsewhere to be more transparent.
It creates the following private functions:
- `Test-EmbeddedInstance`, which does a best-guess at whether or not a particular PowerShell data type represents an embedded cim instance or not. As of the time of this commit, no PowerShell modules were found with data types not covered by this function which were not …
> (IAC-710) Improve DSC Resource Type Handling

- build.ps1
- src/functions/Get-PuppetizedModuleName.ps1
- src/functions/Update-PuppetModuleReadme.ps1
- src/internal/functions/Get-ReadmeContent.ps1
- src/puppet.dsc.psd1
- src/tests/functions/Get-PuppetizedModuleName.Tests.ps1
- src/tests/functions/Get-ReadmeContent.Tests.ps1
- src/tests/functions/Update-PuppetModuleReadme.Tests.ps1
This commit takes an initial pass at adding an automatically generated readme file to the Puppetized module, covering basic usage and clarifying that the module is autogenerated, as well as pointing readers in the right direction for troubleshooting, filing issues, and investigating.
The troubleshooting section is left a little bare as the bulk of this documentation is scheduled to be written in [IAC-716](https://tickets.puppetlabs.com/browse/IAC-716).
This readme should be updated as additional documentation is written to reflect best practices and functionality.
This PR also adds the `Get-PuppetizedName` helper function which returns a munged PowerShell module name for use as a Puppet module name; this was necessary as it was discovered during testing that numerous PowerShell modules …
> (IAC-707) Add Update-PuppetModuleReadme, Get-PuppetizedName

- src/internal/functions/Invoke-PdkCommand.ps1
- src/tests/functions/Invoke-PdkCommand.Tests.ps1
Prior to this PR the `Invoke-PdkCommand` private function only checked the `stderr` logs for a PDK command to verify whether or not it was successful.
Since the PDK does not consistently send information to `stderr` or `stdout` indicating successful completion of a command, this PR updates the success filter to work regardless of output stream.
> (MAINT) Check stdout for pdk success messages

- src/functions/New-PuppetDscModule.ps1
- src/tests/functions/New-PuppetDscModule.Tests.ps1
Prior to this commit the call to `Update-PuppetModuleReadme` was erroneously left out of `New-PuppetDscModule`, meaning that the README that shipped with each auto-generated module was the default template readme supplied by the PDK instead of the useful and specific one generated for each DSC module.
This commit adds the call and updates tests to reflect it.
> (MAINT) Ensure New-PuppetDscModule populates readme

- appveyor.yml
- build.ps1
- extras/install.ps1
- src/functions/New-PuppetDscModule.ps1
- src/internal/functions/Get-CimClassPropertiesList.ps1
- src/internal/functions/Get-DscResourceParameterInfo.ps1
- src/internal/functions/Get-DscResourceParameterInfoByCimClass.ps1
- src/internal/functions/Get-DscResourceTypeInformation.ps1
- src/internal/functions/Get-EmbeddedCimInstance.ps1
- src/internal/functions/Get-TypeParameterContent.ps1
- src/internal/functions/Initialize-DscResourceCimClass.ps1
- src/internal/functions/Test-RunningElevated.ps1
- src/internal/functions/Test-SymLinkedItem.ps1
- src/tests/functions/Get-CimClassPropertiesList.Tests.ps1
- src/tests/functions/Get-DscResourceParameterInfoByCimClass.Tests.ps1
- src/tests/functions/Get-DscResourceTypeInformation.Tests.ps1
- src/tests/functions/Get-EmbeddedCimInstance.Tests.ps1
- src/tests/functions/Initialize-DscResourceCimClass.Tests.ps1
- src/tests/functions/New-PuppetDscModule.Tests.ps1
- src/tests/functions/Test-SymLinkedItem.Tests.ps1
This PR plumbs the `Get-DscTypeInformation` function to be aware of whether or not it is running in an elevated context or not and to retrieve the parameter information by CIM class if it *is* running elevated, or by AST/Resource metadata if not.
It does so by implementing the `Get-DscResourceParameterInfoByCimClass` function, an alternate implementation of `Get-DscResourceParameterInfo`, which could not parse embedded CIM instances. The new function can, but will only work if run as administrator. 
In practice, this means our type attribute definitions for DSC resources with CIM instance properties go from this:
```puppet
dsc_accesscontrollist: {
type: "Array[Hash]",
desc: %q{
Indicates the access control information in the form of an array of instances of the NTFSAccessControlList CIM …
```
> (IAC-740) Map embedded CIM instances if running elevated

- src/internal/functions/Update-PuppetModuleMetadata.ps1
- src/tests/functions/Update-PuppetModuleMetadata.Tests.ps1
The metadata-json-lint tool requires at most 144 characters in the `summary` field. This change truncates the summary accordingly.
See https://github.com/voxpupuli/metadata-json-lint/blob/5ab67f9404ee65da0efd84a597b2ee86152d2659/lib/metadata-json-lint/schema.rb#L99
> Ensure that metadata field `summary` is always less than 144 length

- appveyor.yml
- build.Tests.ps1
- extras/install.ps1
- src/tests/pester.ps1
Follow [AppVeyor's recommendations for handling error conditions in powershell](https://www.appveyor.com/docs/build-configuration/#interpreters-and-scripts).
> (IAC-861) Update CI scripts to fail AppVeyor runs on test failures

- src/functions/New-PuppetDscModule.ps1
- src/internal/functions/ConvertTo-CanonicalPuppetAuthorName.ps1
- src/tests/functions/ConvertTo-CanonicalPuppetAuthorName.ps1
- src/tests/functions/New-PuppetDscModule.Tests.ps1
Prior to this commit it was possible for a user to specify a
Puppet module author name as a string which was not a valid
name - that is, included non-alphanumeric characters and/or
uppercase characters.
This commit adds a private function for canonicalizing the
author name and ensures that the author name is canonicalized
when called for creating a new module.
> (IAC-846) Canonicalize Puppet module author names

- build.Tests.ps1
Testing Around nuget module.
Five tickets opened for the issues seeing about the resources generated.
Since no default values created for local NuGet repository, changed the test workflow to test the generated resources.
Failing testcases are added to pending. Once the defect is fixed we can remove the pending status.
https://tickets.puppetlabs.com/browse/IAC-879
https://tickets.puppetlabs.com/browse/IAC-902
https://tickets.puppetlabs.com/browse/IAC-905
https://tickets.puppetlabs.com/browse/IAC-953
https://tickets.puppetlabs.com/browse/IAC-955
> (IAC-720) Class based testcases

- appveyor.yml
- build.Tests.ps1
- src/internal/templates/static/lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
Prior to this commit specifying a PSDscRunAsCredential to run a DSC resource as was not possible, the run errored unpredictably.
This commit updates the base provider to handle running as another user, including handling logon errors and failures and caching them to prevent recurring failures.
Two limitations in this implementation exist:
1. It is not currently possible to cease processing a resource if there is an error with the credentials (e.g. unauthorized or bad password) so code paths have been introduced to handle this and minimize additional calls to the system.
2. Something in the way that Puppet compares Sensitive values is causing the strict check for canonicalization of retrieved data to fail, resulting in a warning message that claims the values are different while displaying …
> (IAC-804) Implement PSDscRunAsCredential

- src/internal/functions/Update-PuppetModuleMetadata.ps1
- src/tests/functions/Update-PuppetModuleMetadata.Tests.ps1
Prior to this commit the metadata in a puppetized module erroneously
specified requiring pwshlib 0.4.0 or higher; this is insufficient,
because 0.5.0 is the release that implements and includes the base
DSC provider that these puppetized modules rely on.
> (MAINT) Update pwshlib reference to 0.5.0

- src/internal/functions/Get-ReadmeContent.ps1
* There isn't a good way right now to create internal links to other
files in the module that work on both github/gitlab repositories and
also after being rendered on the Forge.
* Added the link to the Troubleshooting section in the repo. Not sure if
there are plans to write a more complete troubleshooting guide, but
that seems fine.
> (maint) Correct links in README

- src/internal/functions/Update-PuppetModuleMetadata.ps1
- src/tests/functions/Update-PuppetModuleMetadata.Tests.ps1
This commit updates the version pin for pwshlib to 0.5.1,
which introduces a fix to the base provider which enables
the resources to work properly during a puppet agent run;
prior to that bugfix, they only work via puppet apply.
> (MAINT) Update version pin for pwshlib

- src/internal/functions/Get-ReadmeContent.ps1
This commit adds the known limitations section to the generated README documentation, clarifying the current incompatibility of the generated modules with the legacy puppetlabs-dsc module.
> (MAINT) Add known limitations to generated readmes

- CHANGELOG.md
This commit adds a changelog to the project in
keeping with the KAC standard and also includes
an unreleased section.
Future pull requests should include, in addition
to documentation and tests, a changelog entry for
the work being done.
> (MAINT) Add project CHANGELOG file

- src/internal/functions/Add-DscResourceModule.ps1
Prior to this commit specifying a module with a prerelease version
would cause an error because the AllowPrerelease flag was not set.
This commit merely enables the puppetizing of prerelease modules but
does not rework the version API to distinguish between them. Because
of the way the modules are currently built, Puppet will not publish
prerelease modules to the forge.
While prerelease versions *can* be used, the maintainers suggest that
this is always a temporary workaround and not a good practice to be
encouraged in production.
> (MAINT) Enable puppetizing prerelease modules

- src/internal/functions/Get-TypeParameterContent.ps1
- src/tests/functions/Get-TypeParameterContent.Tests.ps1
Prior to this commit the desc strings for types were wrapped in `%q{}`, which *should* allow multi-line string description blocks. However, there is a bug in the puppet strings tooling which causes it instead to write the `%q{}` as well as everything inside, which looks _strange_ in the markdown.
This commit modifies the type generation to instead use a single-quoted string for the desc blocks, without newlines. If the help is empty, it now specifies a string with a single whitespace in it.
Failure to include the single whitespace broke puppet strings parsing, so this ensures that no docs are written if they are not specified, keeping the reference documentation readable if not correct from a markdown-linting perspective.
- Resolves #66
> (GH-66) Ensure type desc strings parse for reference

- src/internal/functions/Get-DscResourceParameterInfoByCimClass.ps1
Prior to this commit nested CIM instances would get an incorrect Puppet type definition, where optional types would not be prefaced as such.
This commit updates the section of `Get-DscResourceParameterInfoByCimClass` which handles the Puppetization of the data type for nested CIM instances, adding a final check to validate whether or not the property is actually mandatory. This ensures that the types are correctly defined and can be passed as expected in a manifest.
- Resolves #71
> (GH-71) Fix type def of props with optional nested cim instances

- src/internal/functions/Get-ReadmeContent.ps1
This commit adds two new subsections to the generated README for Puppetized modules, clarifying which properties are passed to `Invoke-DscResource` by the provider.
Resolves #72
> (GH-72) Clarify property usage in generated readme

- Vagrantfile
- extras/install.ps1
- extras/profile.ps1
This commit updates the vagrant provisioning to prepare for the
installation of rubies via uru/rubyinstaller and improves the
dev ux in the vagrant box by adding posh-git and a helper function
for creating a new Gemfile.local with the pry gems.
This should enable pry debugging during generated module testing.
NB: The automatic ruby installer is non-functional, users will need
to run Install-Ruby interactively when first logging into the new
Vagrant box.
- Resolves #94
> (GH-94) Add debugging env to vagrant

- src/internal/functions/Get-TypeParameterContent.ps1
Prior to this commit the Get-TypeContent function would sometimes pass
a null object to Get-TypeParameterContent which would then write a non-
functional attribute definition, breaking the type.
I was not able to discover how this was happening, but this small patch
seemed like a sensible enough guard given prioritization.
> (MAINT) Only write attributes if parameter is not null

- src/internal/functions/Get-DscResourceParameterInfoByCimClass.ps1
When parsing a Struct Puppet type, upcased keys will be interpreted
as Puppet Types themselves, leading to a catalogue compilation error.
This commit ensures that the keys in a struct are downcased.
> (MAINT) Ensure struct keys are downcased

- src/internal/functions/Get-DscResourceParameterInfoByCimClass.ps1
- src/internal/functions/Get-TypeParameterContent.ps1
Prior to this commit the type generator ignored read-only DSC Resource properties. This commit ensures that if the read-only flag is set on a DSC Resource property it is included in the generated type with the appropriate Resource API behaviour.
- Resolves #80
> (GH-80) Typify read only properties

- build.ps1
- src/functions/New-PuppetDscModule.ps1
- src/internal/functions/Add-DscResourceModule.ps1
- src/tests/functions/Add-DscResourceModule.Tests.ps1
Prior to this commit the `AllowPrerelease` flag was always passed to `Save-Module` in the `Add-DscResourcModule` function. This meant that if no version was specifically passed during a call to `New-PuppetDscModule` or `Add-DscResourceModule` they would always default to the latest version on the Gallery *including* pre- release versions which is unexpected UX.
This PR ensures that prerelease versions are only puppetized if the `AllowPrerelease` switch is specified and adds that parameter to both functions.
- Resolves #85
> (GH-85) Make puppetizing prerelease modules switchable

- src/internal/functions/Update-PuppetModuleMetadata.ps1
- src/tests/functions/Update-PuppetModuleMetadata.Tests.ps1
This commit raises the lower bound for the pwshlib dependency to 0.6.1 and the upper bound for Puppet to 8.0.0 in accordance with changes in the provider and the stable release of Puppet 7 respectively.
> (MAINT) Update version pins for metadata.json

- extras/install.ps1
- extras/util.ps1
- publish.ps1
- src/internal/functions/Get-PuppetModuleVersion.ps1
Add the following functions to a dot-sourcable script in the extras folder:
- `ConvertTo-VersionBuild`: Break a DSC Puppet version into the four-section version and build for easy incrementing and checking.
- `Get-LatestBuild`: Given a list of DSC Puppet versions, return only the latest build of each unique version to enable incrementing and rebuilding.
- `ConvertFrom-VersionBuild`: Turn a given VersionBuild object back into a DSC Puppet version string like '1.2.3-4-1'
- `Get-ForgeModuleInfo`: Return the name, list of releases, and PowerShell module metadata back from a given DSC module on the forge
- `Get-ForgeDscModules`: Retrieve all of the DSC modules on the forge, including their name, list of releases, and PowerShell module metadata
- `Update-ForgeDscModule`: Update one or more …
> (MAINT) Add Util Functions

- src/functions/New-PuppetDscModule.ps1
Following this change and building 2 new DSC modules I can confirm they are now deposited in `lib/puppet_x/<module_name>/dsc_resources` instead of `lib/puppet_x/dsc_resources`.
Resolves #115 #
> (GH-75) - PowerShell module dependencies are installable side by side

- CHANGELOG.md
- src/puppet.dsc.psd1
Prior to this commit some users with old versions of PowerShellGet and
PackageManagement would try using the AllowPreRelease switch and get an
error indicating that switch was not available.
This commit adds a modern version of PowerShellGet as a dependency which
itself has a dependency on PackageManagement.
- Fixes #111
> (GH-111) Add PowerShellGet as module dependency

- src/internal/functions/Update-PuppetModuleMetadata.ps1
- src/tests/functions/Update-PuppetModuleMetadata.Tests.ps1
The minimum compatible version of pwshlib must be raised to 0.7.0
to take advantage of the updated logic to work with the new vendored
module paths from #75.
> (GH-75) Update pwshlib pin in generated module metadata

- src/internal/functions/Update-PuppetModuleMetadata.ps1
Prior to this commit the Summary string in the metadata would erroneously include newlines. This commit obviates that error.
> (MAINT) Fix metadata summary entry definition

- CHANGELOG.md
- src/internal/functions/Test-DscResourcePropertyParameterStatus.ps1
The `OID` and `KeyUsage` properties of the `CertReq` DSC Resource cannot be returned, per the implementation details for that resources own `Get-TargetResource` function:
- https://github.com/dsccommunity/CertificateDsc/blob/main/source/DSCResources/DSC_CertReq/DSC_CertReq.psm1#L225-L226
This commit adds those two property names to the hard-coded list of DSC Resource properties which should be treated as parameters in Puppet.
> (MAINT) Add CertReq parameters to hard-coded list

- CHANGELOG.md
- src/internal/functions/Add-DscResourceModule.ps1
- src/tests/functions/Add-DscResourceModule.Tests.ps1
Prior to this commit some modules, like the PrintManagementDsc module,
include dependencies in the RequiredModules key of their manifest which
cannot be found on the public gallery. This caused errors during the build
process as the ModulePath is temporarily munged.
This commit overcomes that problem by vendoring the dependencies in, even if
they cannot be found in the specified repo, so long as they are available on
the machine puppetizing the PowerShell module containing DSC Resources.
- Resolves #113
> (GH-113) Vendor modules not found in module repo

- CHANGELOG.md
- src/functions/New-PuppetDscModule.Tests.ps1
- src/functions/New-PuppetDscModule.ps1
Prior to this commit, the `New-PuppetDscModule` command could fail unexpectedly if PSRemoting is not enabled; when attempting to map CIM instances the command would fail with an esoteric null error.
This commit adds an explicit check to the command which validates that PSRemoting is enabled if running as administrator and errors clearly if it is not.
- Resolves #133
> (GH-133) Throw if PSRemoting is disabled

- .gitignore
- docs/about_Puppetizing_Custom_Modules.md
This PR adds initial documentation for Puppetizing PowerShell modules with DSC Resources not found on the public gallery.
It also updates the .gitignore to correctly manage `about*` docs.
- Resolves #64
> (GH-64) Add docs for customizing private modules

- CHANGELOG.md
- src/functions/New-PuppetDscModule.Tests.ps1
- src/functions/New-PuppetDscModule.ps1
- src/internal/functions/Get-ReadmeContent.Tests.ps1
- src/internal/functions/Get-ReadmeContent.ps1
- src/internal/functions/Update-PuppetModuleReadme.Tests.ps1
- src/internal/functions/Update-PuppetModuleReadme.ps1
This commit corrects a bug where the auto-generated readme was missing the PowerShell and Puppet module names from various locations in the output markdown.
Those values were not being passed by New-PuppetDscModule to Update-PuppetModuleReadme.
Also includes work to increase parameter validation within `Update-PuppetModuleReadme` and `Get-Readmecontent` to help catch any empty or null values and make parameters mandatory.
Resolves #153
> (GH-153) Ensure generated readme contains module name info

- .github/workflows/spec.yml
- acceptance/Basic.Tests.ps1
This commit moves the acceptance tests to their own folder in preparation for adding multiple acceptance test files. In the current design, all acceptance tests would need to live in a single file which makes it hard to maintain and reason about.
This commit moves the existing acceptance tests to acceptance/Basic.Tests.ps1 and updates the CI config to look in the correct place.
> (MAINT) Move acceptance tests to folder and refactor acceptance testing CI Job

- Vagrantfile
- extras/install.ps1
This commit updates the vagrant file to install the full suite of software for development and testing.
It also updates the install script to:
- Fixup the style where needed
- Add conemu to the list of software to install outside of CI
- Only set WinRM if the Full flag is passed
- Install chocolatey if it is not already installed
- Update the session environment after installing software
- Turn on installing multiple dev rubies for use outside of CI
> (MAINT) Update install script and vagrantfile

- .github/workflows/spec.yml
- acceptance/MultiModule.Tests.ps1
- examples/webserver/webserver_template.pp
- examples/webserver/website/index.html
- extras/install.ps1
- extras/invoke_tests.ps1
Prior to this PR, the only acceptance tests for puppetized modules were single-module and single-resource.
This PR adds a new set of acceptance tests which validate using native Puppet resources and puppetized DSC Resources side by side, and ensures that multiple DSC resources of the same and different type and across modules can interoperate successfully.
> (GH-62) Add acceptance testing for multi-module scenario

- CHANGELOG.md
- acceptance/Basic.Tests.ps1
- src/internal/functions/Get-DscResourceImplementation.Tests.ps1
- src/internal/functions/Get-DscResourceImplementation.ps1
- src/internal/functions/Get-DscResourceTypeInformation.Tests.ps1
- src/internal/functions/Get-DscResourceTypeInformation.ps1
- src/internal/functions/Get-ReadmeContent.ps1
- src/internal/functions/Get-TypeContent.Tests.ps1
- src/internal/functions/Get-TypeContent.ps1
Prior to this PR, the generated types did not include their implementation information.
This PR ensures that granular implementation information is added to the `dscmeta_resource_implementation` key, distinguishing between MOF-based, class-based, binary, and composite implementations instead of only Powershell/binary/composite.
To do so, this PR:
1. Adds the `Get-PowerShellDscResourceType` private function, which has logic to determine if a DSC Resource with an `ImplementedAs` value of `PowerShell` is MOF-based or class-based
2. Ensures that the `Get-DscResourceTypeInformation` private function uses `Get-PowerShellDscResourceType` to capture the implementation of the DSC Resource being introspected
3. Ensures that the `dscmeta_resource_implementation` key is added to the generated Puppet …
> (GH-172) Add implementation to generated types

- CHANGELOG.md
- src/internal/functions/Get-DscResourceParameterInfoByCimClass.Tests.ps1
- src/internal/functions/Get-DscResourceParameterInfoByCimClass.ps1
Prior to this PR the builder defined the Puppet type for a nested cim instance's type as a string of its value, ie `'SomeInstanceType'`.
This caused runtime errors when passing the `cim_instance_type` during a Puppet run as this is not a valid data type.
This PR updates the mapping of a nested CIM Instance into a Puppet property by defining the `cim_instance_type` as a single-value enum, such as `Enum['SomeINstanceType']` - this obviates the runtime error.
> (MAINT) Define nested cim instance types as enums

- CHANGELOG.md
- src/internal/functions/Get-ReadmeContent.Tests.ps1
- src/internal/functions/Get-ReadmeContent.ps1
> (GH-186) Handle missing Project URI in PowerShell module metadata

- CHANGELOG.md
- docs/about_Puppetized_Module_Invocation.md
This PR adds the new `about_Puppetized_Module_Invocation` help file as concept documentation to enumerate how the DSC Base Provider works from a user's perspective.
Resolves #74
> (GH-74) Add Concept docs for module invocation

- .github/workflows/puppetize.yml
Prior to this PR we were importing an unreleased version of Puppet.Dsc that had a fix for the search command. A new version of Puppet.Dsc has now been released that contains this fix.
This PR removes the local import from the Build Matrix step.
> (MAINT) Remove local module import

- .github/workflows/puppetize.yml
This PR adds the workflow_dispatch trigger. This will enable us to execute this workflow ad-hoc.
Issue #199 talks about what a workflow dispatch option could look like in the future.
> (MAINT) Add workflow_dispatch trigger

- README.md
As per issue #215, we are adding a new section to the readme to warn users of possible errors generated by attempting to assign a wrong value type by mistake.
> (MODULES-11310) README warning about types

- .github/workflows/spec.yml
- src/functions/New-PuppetDscModule.ps1
- src/internal/functions/Initialize-PuppetModule.ps1
Prior to this commit it was not possible to specify the version of pdk-templates that would be used when puppetizing a Dsc module.
PDK help sugegsts that the default ref is 2.5.0, however in practice it would pull down the latest tag from the pdk-templates repository. At the time of commit, this was 2.6.0.
The above diff causes some issues when puppetizing a resource due to gem incompatibilities.
This commit adds a new parameter called PDKTemplateRef to `New-PuppetDscModule` and `Initialize-PuppetModule` so that users can optionally provide a different pdk-templates version.
The default value has been set to 2.5.0.
> (CONT-257) Add PDKTemplateRef parameter

- src/internal/functions/Get-PuppetDataType.Tests.ps1
- src/internal/functions/Get-PuppetDataType.ps1
This change more closely mimics the functionality of [the original `dsc` module](https://forge.puppet.com/modules/puppetlabs/dsc), allowing enum values to be passed either as specified in the schema or their lowercase variants. 
Resolves Issue #216
> Adding case insensitive enum values

- .github/workflows/puppetize.yml
- .github/workflows/repuppetize.yml
Prior to this PR the FORGE_TOKEN environment variable was missing from the puppetize and repuppetize publish steps. This caused the workflow to fail.
This PR adds the env as required.
> (MAINT) Fix missing FORGE_TOKEN env

- src/Puppet.Dsc/internal/functions/Get-PuppetDataType.Tests.ps1
- src/Puppet.Dsc/internal/functions/Get-PuppetDataType.ps1
Prior to this change enums with a single value would be generated with a lowercase counterpart but the enum definition was malformed.
For example, given the the value `Yes` the following enum would be generated:
`Optional[Enum['Yes' 'yes]]`
This was happening because when a PowerShell array has a single value it will output a string.
This meant that when being assigned the lowercase variant of the value a string concatination occured causing the join on the next line to be ineffective.
This change updates the flow to use a `System.Collections.ArrayList` so that we will always have the expected datastructure.
After this change, given the value `Yes' the following enum would be generated:
`Optional[Enum['Yes', 'yes]]`
This is expected syntax and does not cause Puppets syntax parser to raise …
> (GH-240) Fix incorrect enum generation

- .github/workflows/puppetize.yml
- src/Puppet.Dsc/functions/New-PuppetDscModule.ps1
Use pdk templates ref 3.0.0 instead of 2.5.0 as the puppetise workflow seems to have a problem with the `pdk new module` command
> (CONT-1152) Use pdk templates ref 3.0.0

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .github/workflows/puppetize.yml
- .github/workflows/repuppetize.yml
- dsc_resources.yml
- src/Puppet.Dsc/functions/New-PuppetDscModule.Tests.ps1
- src/Puppet.Dsc/functions/New-PuppetDscModule.ps1
- src/Puppet.Dsc/internal/functions/Invoke-BundleInstall.ps1
This PR changes the puppetize workflow to run at 6am on the 1st and 15th day of each month.
It also includes a change which allows the workflow to gather the top 50 downloaded DSC modules using the forge API, and puppetize them.
This only creates a job for the modules which are out of sync with the PS Gallery, not all modules will create a job so this will keep compute resources down.
This PR also contains a number of smaller maintenance fixes:
Updated the naming of the Install-Gems function to Invoke-BundleInstall as per the powershell styling guidelines.
Adds a nightly workflow for reporting
Adds 7ZipArchiveDsc to dsc_resources.yml as the forge name does not match the name found for this module on PSGallery, so prevents a mismatch between the forge and psgallery apis.
🟢 Spec tests.
🟢 …
> (CAT-1322) - Rename Install-Gems to Invoke-BundleInstall & Run Puppetize Biweekly

- .gitignore
- docs/architecture/decisions/0001-force-ensurable.md
- src/Puppet.Dsc/internal/functions/Get-TypeContent.ps1
- src/Puppet.Dsc/internal/functions/Get-TypeParameterContent.ps1
This PR adds a `ensurable` property to each resource which does not already have an ensure property defined. This has a couple of beneifts:
1. Prevents issues as seen in CAT-1484, where puppet namevars and DSC keys differences arise. By default, puppet will ignore namevar changes if they are the only atrtibutes passed in a manifest. This is a design of puppet and makes sure as namevars should only identify a resource. DSC's key values behave differently to this.
2. Will now clearly show in docs that the resource CANNOT be ensured.
The property sets a default of 'false' and will only accept a value of 'false'. The value will not need to be specified in manifests.
Puppet will not update a resource if only namevars are passed. We can see in the puppet source code that there is no logic to …
> (CAT-1484) - Add ensurable property to resource

- .github/workflows/puppetize.yml
- .github/workflows/repuppetize.yml
Puppet.Dsc module was being cached by github actions, meaning we repuppetized our modules with an older version of the module.
We should always use the most up-to-date release of the Puppet.Dsc module, so have removed it from the cache.
> (maint) - Remove Puppet.Dsc from module cache

- src/Puppet.Dsc/internal/functions/Get-ReadmeContent.ps1
This PR adds a warning to each generated modules readme about the use of sensitive data with script block logging enabled. As per microsoft's own recommendation, protected event logging should also be enabled to encyrpt this data.
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_logging_windows?view=powershell-7.4#protected-event-logging:~:text=It%27s%20recommended%20to%20enable%20Protected%20Event%20Logging%2C%20as%20described%20below%2C%20when%20using%20Script%20Block%20Logging%20for%20anything%20other%20than%20diagnostics%20purposes.
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_logging_windows?view=powershell-7.4#protected-event-logging
> (maint) - Add disclaimer for script block logging

- src/Puppet.Dsc/internal/functions/Update-PuppetModuleMetadata.Tests.ps1
- src/Puppet.Dsc/internal/functions/Update-PuppetModuleMetadata.ps1
bumps the minimum required puppetlabs/pwshlib to 1.2.0, as dsc_timeout logic is only present in these module versions.
> bump required pwshlib to 1.2.0 and greater

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .github/workflows/puppetize.yml
- .github/workflows/release.yml
- .github/workflows/release_prep.yml
- .github/workflows/repuppetize.yml
Bumps potatoqualitee/psmodulecache to v6.2.1 to no longer pull in actions/cache v3
Bumps codecov/codecov-action to v5 to no longer pull in actions/cache v3
Bumps actions/checkout to latest v4
> (maint) - fix broken nightlies
