.gitignore
Vagrantfile

This commit adds a vagrant box that pulls in the project
dependencies to make working on the code base easier.

Add Vagrantfile for reproducible tests and development environment

---

build.ps1

This commit updates the Build script slightly in advance of
IAC-665, ensuring that the metadata for the created Puppet
module:
- Can have an author other than the current user
- Pulls the summary from the PowerShell module
- Adds the appropriate links to source, docs, and issues
- Outputs only the correct operating systems for support
- Writes the JSON without unicode escape codes for versions

(IAC-699) Improve Puppet module metadata

---

build.Tests.ps1
extras/install.ps1

Request for a review
Specify the PuppetModuleAuthor as testuser to get consistent test results on different environment
Pinned to the previous version of PSModuleDevelopment for fixing the null valued expression error.

(IAC-862) specify moduleauthorname to tests

---

src/internal/functions/Get-ProviderContent.ps1
src/tests/functions/Get-ProviderContent.Tests.ps1

Remove underscore from ProviderName to fix the resources generated from nuget module.

(IAC-879) fix providername,Underscores are not valid.

---

src/internal/templates/static/lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb

Prior to this commit the get method was invoked for a unique resource
regardless of whether or not that information had already been
retrieved in a prior query or not.
This commit adds a new cache for query results to reduce unneccesary
operations, thus speeding things along and reducing resource
utilization.
This commit also uses a new method, fetch_cached_hashes, to verify
if a given set of hashes can be looked up in a cache; in other words,
if the value of a passed hash is a subset of any of the cached hashes,
the method will return the full value of the cached hash.
This new method has been used for both the canonical and query caches.
Further, this commit updates the behavior of the get method to only
invoke if the name hash for the resource has not already been queried;
otherwise it …

(IAC-895) Implement query caching

---

src/functions/New-PuppetDscModule.ps1
src/internal/functions/Add-DscResourceModule.ps1
src/tests/functions/Add-DscResourceModule.Tests.ps1
src/tests/functions/New-PuppetDscModule.Tests.ps1

Request for a review
New-PuppetDscModule function is added with new parameter Repository to download from any specific repository.By default it will be PSGallery
Add-DscResourceModule function is also modified to take the parameter Repository which is called inside the New-PuppetDscModule function.
Unit tests are added and modified for this new parameter added in the functions New-PuppetDscModule , Add-DscResourceModule

(IAC-844) Allow using a local PSRepository

---

src/internal/functions/Update-PuppetModuleMetadata.ps1
src/tests/functions/Update-PuppetModuleMetadata.Tests.ps1

This makes it searchable on the Forge via
* https://forge.puppet.com/tags/windows
* https://forge.puppet.com/tags/puppetdscbuilder
* https://forge.puppet.com/tags/dsc

Tag the generated module

---

src/internal/functions/Update-PuppetModuleChangelog.ps1
src/tests/functions/Update-PuppetModuleChangelog.Tests.ps1

This commit ensures that the puppetized modules will include
changelog entries tied to the PowerShell module, if possible.

(MAINT) Add function to update changelog

---

src/internal/functions/Get-ReadmeContent.ps1

(GH-59) Correct text in troubleshooting section

---

extras/util.ps1
src/internal/functions/Update-PuppetModuleMetadata.ps1
src/tests/fixtures/PowerShellGet.psd1
src/tests/functions/Update-PuppetModuleMetadata.Tests.ps1

(GH-89) Fix various bugs for puppetization

---

src/internal/functions/Get-ReadmeContent.ps1

This PR adds a section into the autogenerated README to provide end users an example of how to use PSCredentials and CIMInstances.

(GH-114) - Adding PSCredential and CIM Instance examples

---

Acceptance.Tests.ps1
CHANGELOG.md
README.md
appveyor.yml
src/functions/New-PuppetDscModule.Tests.ps1
src/functions/New-PuppetDscModule.ps1
src/internal/functions/Update-PuppetModuleFixture.Tests.ps1
src/internal/functions/Update-PuppetModuleFixture.ps1

(GH-93) Allow alternate fixture references

---

src/internal/functions/Get-DscResourceParameterInfoByCimClass.ps1
src/internal/functions/Get-ReadmeContent.ps1
src/puppet.dsc.psd1
src/tests/fixtures/metadata.json

Removal of any offensive or inappropriate terminology from the code base.

(IAC-1449) - Removal of Inappropriate Terminology

---

.github/workflows/spec.yml
appveyor.yml

(GH-148) - Migrate Unit/General tests from Appveyor to GitHub Actions

---

.github/workflows/spec.yml

A fix for the PDK issue that was blocking this has gone in

(GH-148) Activate acceptance tests

---

examples/class_based.pp
examples/complex.pp
examples/nested_cim_instance.pp
examples/simple.pp

This PR adds several small example manifests which use Puppetized DSC Resources to change system state.

(MAINT) Add basic use examples

---

.github/workflows/spec.yml
README.md
src/internal/functions/Update-PuppetModuleFixture.Tests.ps1

This PR fixes acceptance tests by updating  git:// to https://.

(GH-212) Update git:// to https://

---

.github/ISSUE_TEMPLATE/puppetize-request.md
.github/ISSUE_TEMPLATE/re-puppetize-request.md

A small PR that attempts to fix a few issues with the current issue templates.

(MAINT) Cleanup issue templates

---

.github/workflows/ci.yml
.github/workflows/puppetize.yml
.github/workflows/repuppetize.yml
src/Puppet.Dsc/functions/New-PuppetDscModule.ps1
src/Puppet.Dsc/internal/functions/Install-Gems.ps1

(maint) - Update PDK Install

---

README.md

(maint) - Fix CODEOWNERS badge

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
.github/workflows/puppetize.yml
.github/workflows/repuppetize.yml

Ensures puppetize works until next pdk release.

(MAINT) - temp pin pdk 2.7.1

---

docs/architecture/decisions/0001-force-ensurable.md

Adding an illustration of how namevar works with a Puppet File resource

(maint) - Add an illustration to the design document.

---

src/Puppet.Dsc/internal/functions/Update-PuppetModuleMetadata.Tests.ps1
src/Puppet.Dsc/internal/functions/Update-PuppetModuleMetadata.ps1

Add Puppet 8 Support and Drop Puppet 6.

(CAT-1454) - Add Puppet 8/Drop Puppet 6

---

.github/workflows/ci.yml
scripts/invoke_tests.ps1

(CAT-1618) - Add code coverage to ci

---

.github/workflows/mend.yml

(CAT-1659) - Add mend scanning to repo

---

.github/workflows/mend.yml

(maint) - Remove redundant conditional checkout

---

src/Puppet.Dsc/internal/functions/Update-PuppetModuleMetadata.Tests.ps1
src/Puppet.Dsc/internal/functions/Update-PuppetModuleMetadata.ps1

(feat) - Add windows 2022 to modules

---

.github/workflows/ci.yml

(maint) Update ci.yml to use codecov v4 action and adding conditional

---

CHANGELOG.md
docs/about_Puppetized_Module_Invocation.md
src/Puppet.Dsc/internal/functions/Get-ProviderContent.ps1

Fixes https://github.com/puppetlabs/Puppet.Dsc/issues/299

Fix autoload issue by replacing require to require_relative
